### ISSUE TITLE
New wiki page for documenting using localstack with cloud-based tools

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#105]
### 💡 Description

See https://github.com/NASA-PDS/data-upload-manager/pull/167

**Comment by jordanpadams** [comment]
https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Getting-Started-with-Localstack

**Comment by nutjob4life** [comment]
Hi @collinss-jpl I'm going through your [wiki page](https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Getting-Started-with-Localstack) and I'm stuck on the step where you find the "Hobby License".

Under "Workspace", I went to "User & Licenses" and I have this:

<img width="763" alt="Screenshot 2024-10-22 at 5 24 05 PM" src="https://github.com/user-attachments/assets/e2be48a3-50c0-46d9-a367-2fb5b4d48a8b">

I tried both "Subscriptions" → "Add a New Plan" or the "Start a new plan" link directly and get to this page:

<img width="821" alt="Screenshot 2024-10-22 at 5 24 44 PM" src="https://github.com/user-attachments/assets/ff006dab-3728-4572-a275-dc676b50849c">

However this page only has 4 options:

- Trial
- Starter
- Team
- Enterprise

Where did you find "Hobby License"?

**Comment by sdcolli1** [comment]
@nutjob4life Took me a second to remember, but the trick is when first creating a username and password (via https://app.localstack.cloud/sign-up), then you should be presented with this menu:

<img width="944" alt="Screenshot 2024-10-23 at 9 47 45 AM" src="https://github.com/user-attachments/assets/46833916-87d6-49eb-b2d7-ef126e3b31ef">

If you've used GitHub SSO it may bypass this option though? Maybe retry signing up with a new email address?

@jordanpadams This has me thinking that if we're going to advertise that we're leveraging localstack for things like DUM integration tests, maybe its time to consider springing for a Team/Enterprise license or three?

**Comment by nutjob4life** [comment]
@collinss-jpl that's the trick! Yeah, I signed in with GitHub. I'll re-create an account with an email address.

**Comment by jordanpadams** [comment]
@collinss-jpl @nutjob4life unfortunately, we have less than no money at this time. we can reevaluate in the second half of the fiscal year, but unfortunately that is where we are at.

**Comment by nutjob4life** [comment]
@jordanpadams we're grateful where you _did_ spend it 🙏

**Comment by sdcolli1** [comment]
I have added a blurb to the wiki page on signing up with an email address so as to get the option for the Hobbyist license.

**Comment by nutjob4life** [comment]
![excelsior-stan-lee](https://github.com/user-attachments/assets/e4bebd02-fabf-4d52-9547-53956ff1c05e)
