### ISSUE TITLE
[website] NAIF missing `Facility` in pds.nasa.gov sidebar

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#11]
## 📜 To Reproduce
1. Go to pds.nasa.gov
2. NAIF is incorrect in sidebar:

<img width="348" alt="Screen Shot 2021-06-28 at 12 46 14 PM" src="https://user-images.githubusercontent.com/33492486/123695248-2dd56180-d80f-11eb-94c8-f44ffd9b83bc.png">

## 🕵️ Expected behavior

NAIF = **Navigation** & Ancillary Information **Facility** (NAIF)

**Comment by c-suh** [comment]
Resolved: https://pds.nasa.gov/
