### ISSUE TITLE
Generate Draft B12.0 RDD

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#15]

**Comment by tloubrieu-jpl** [comment]
@jordanpadams is it 12.1 or 12.0 ?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl updated

**Comment by jordanpadams** [comment]
Draft complete and submitted with TRR https://nasa-pds.github.io/releases/12.0/rdd.html
