### ISSUE TITLE
viewHostProfile.jsp never returns useful information

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/PDS-Software-Issues-Repo#19]
Briefly, we return bad search results for any PDS3 instrument host. The code in here always fails, e.g.:
      https://pds.nasa.gov/ds-view/pds/viewHostProfile.jsp?INSTRUMENT_HOST_ID=CO

From what I can see on
    pds-gamma:/usr/local/tomcat/webapps/ds-view/pds/viewHostProfile.jsp
  this call always returns null:
        SolrDocument hostObj = pds3Search.getInstHost(hostLid);
  where hostLid in this case would be "co". I mucked around, and even specifying a real LID or more of the LID like "spacecraft.co" fails. That's even though searching for PDS3 missions works, and that code (viewMissionProfile.jsp) is very similar, and this works
        SolrDocument msnObj = pds3Search.getMission(missionLid);
  where missionLid = "cassini-huygens"

**Comment by jordanpadams** [comment]
@rchenatjpl I think I fixed this here: https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewHostProfile.jsp?INSTRUMENT_HOST_ID=CO 

pull request for the code change is here (internal JPL github): https://github.jpl.nasa.gov/PDSEN/pds4-java/pull/136

**Comment by jordanpadams** [comment]
as a note, the problem was the Solr index is storing instrument hosts case-sensitive. So the values being submitted to the query needed to be uppercase.

**Comment by c-suh** [comment]
PR approved and closed, and the fix is operational: https://pds.nasa.gov/ds-view/pds/viewHostProfile.jsp?INSTRUMENT_HOST_ID=CO
