### ISSUE TITLE
Improve internal deployment documentation

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/PDS-Software-Issues-Repo#35]
## 💪 Motivation
...so that all the SAs expectation are met
See https://wiki.jpl.nasa.gov/pages/viewpage.action?spaceKey=PDSEN&title=Software+Installation+and+Deployment+Guides

## 📖 Additional Details

- [x] Get SA's checklist from Rojeh (UCS, ASR, code scan, accessibility status: public, outside JPL, authentication...)
- [x] Document the status of each application regarding this checklist
- [x] Add architecture documentation at the upper level of multi components application

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by c-suh** [comment]
Asked SAs about the status of existing applications in https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-2099. Have reworked the flowchart as Thomas requested; it's linked at the top of the Software Installation and Deployment, and Thomas as approved it.

**Comment by tloubrieu-jpl** [comment]
A first version of this documentation is now available
