### ISSUE TITLE
Update all GitHub Actions to use checkout@v3 and cache@v3

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#41]
## 💡 Description

<img width="1271" alt="Screen Shot 2022-10-12 at 11 44 03 AM" src="https://user-images.githubusercontent.com/33492486/195423115-ed5927bc-1469-43fc-bfa1-35c5561f097b.png">

Per actions execution, @v2 will soon be deprecated and these won't work

**Comment by jordanpadams** [comment]
@ramesh-maddegoda @nutjob4life @jimmie @tloubrieu-jpl as we are working in repos, let's keep in mind to update the GitHub Actions YAML files to use the newer versions of these steps in the workflows.

**Comment by nutjob4life** [comment]
Looks like the `checkout@v3` and `cache@v3` actions are API-compatible with `@v2` so this should be trivial 😅

**Comment by nutjob4life** [comment]
The following repositories have pull requests pending that address the `@v3` upgrades:

-   [archive-analytics](https://github.com/NASA-PDS/archive-analytics)
-   [deep-archive](https://github.com/NASA-PDS/deep-archive)
-   [doi-service](https://github.com/NASA-PDS/doi-service)
-   [doi-ui](https://github.com/NASA-PDS/doi-ui)
-   [feedback-widget](https://github.com/NASA-PDS/feedback-widget)
-   [github-actions-base](https://github.com/NASA-PDS/github-actions-base)
-   [harvest](https://github.com/NASA-PDS/harvest)
-   [mi-label](https://github.com/NASA-PDS/mi-label)
-   [naif-pds4-bundler](https://github.com/NASA-PDS/naif-pds4-bundler)
-   [nasa-pds.github.io](https://github.com/NASA-PDS/nasa-pds.github.io)
-   [pds-api](https://github.com/NASA-PDS/pds-api)
-   [pds-api-pythonlib](https://github.com/NASA-PDS/pds-api-pythonlib)
-   [pds-api-service](https://github.com/NASA-PDS/pds-api-service)
-   [pds-github-util](https://github.com/NASA-PDS/pds-github-util)
-   [PDS-Pipelines](https://github.com/NASA-PDS/PDS-Pipelines)
-   [pds-registry-app](https://github.com/NASA-PDS/pds-registry-app)
-   [pds-view](https://github.com/NASA-PDS/pds-view)
-   [pds3-product-tools](https://github.com/NASA-PDS/pds3-product-tools)
-   [pds4-graph](https://github.com/NASA-PDS/pds4-graph)
-   [pds4-information-model](https://github.com/NASA-PDS/pds4-information-model)
-   [pds4-jparser](https://github.com/NASA-PDS/pds4-jparser)
-   [pdsen-corral](https://github.com/NASA-PDS/pdsen-corral)
-   [pdsen-maven-parent](https://github.com/NASA-PDS/pdsen-maven-parent)
-   [PLAID](https://github.com/NASA-PDS/PLAID)
-   [product_relationships](https://github.com/NASA-PDS/product_relationships)
-   [registry-api](https://github.com/NASA-PDS/registry-api)
-   [registry-common](https://github.com/NASA-PDS/registry-common)
-   [registry-crawler-service](https://github.com/NASA-PDS/registry-crawler-service)
-   [registry-harvest-cli](https://github.com/NASA-PDS/registry-harvest-cli)
-   [registry-harvest-service](https://github.com/NASA-PDS/registry-harvest-service)
-   [registry-loader](https://github.com/NASA-PDS/registry-loader)
-   [registry-mgr](https://github.com/NASA-PDS/registry-mgr)
-   [roundup-action](https://github.com/NASA-PDS/roundup-action)
-   [sumo-tools](https://github.com/NASA-PDS/sumo-tools)
-   [supplementer](https://github.com/NASA-PDS/supplementer)
-   [template-repo-java](https://github.com/NASA-PDS/template-repo-java)
-   [template-repo-python](https://github.com/NASA-PDS/template-repo-python)
-   [tracking-service](https://github.com/NASA-PDS/tracking-service)
-   [transform](https://github.com/NASA-PDS/transform)
-   [wds-react](https://github.com/NASA-PDS/wds-react)
-   [wds-web](https://github.com/NASA-PDS/wds-web)
-   [wds-wordpress](https://github.com/NASA-PDS/wds-wordpress)
-   [web-analytics](https://github.com/NASA-PDS/web-analytics)

The [validate](https://github.com/NASA-PDS/validate) repository was already upgraded to `@v3`

**Comment by jimmie** [comment]
Largely done - awaiting the plethora of PR's to be approved.

**Comment by tloubrieu-jpl** [comment]
It sounds like all the PR have been merged, I moving this ticket to review

**Comment by nutjob4life** [comment]
![dancing](https://user-images.githubusercontent.com/814813/204647803-404be294-a4c7-4f9a-ac63-29d8c4e8df0e.gif)
