### ISSUE TITLE
As a software user, I want to see the known bugs for a component release 

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/PDS-Software-Issues-Repo#49]
## 🧑‍🔬 User Persona(s)

software user

## 💪 Motivation
...so that I can quickly see the known bugs and for each 'major/high' criticality bug, find a work-around.

## 📖 Additional Details

This is a feedback from the DDR review on 11/31/2022.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

### Skipping I&T Rationale
i&t.skip label applied because this is an internal tracking mechanism with no affect on the software delivered.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl as a heads up, whenever we create requirements, we should be sure to set a priority (p.must-have, p.should-have, p.could-have, p.wont-have) prior to removing the `triage-needed` label.

**Comment by tloubrieu-jpl** [comment]
ok, thanks @jordanpadams

**Comment by tloubrieu-jpl** [comment]
That should be added in the release notes.

**Comment by tloubrieu-jpl** [comment]
I tried to update the parameters of the automated release note by following instructions on https://github.com/github/docs/blob/main/content/repositories/releasing-projects-on-github/automatically-generated-release-notes.md but the only allows to select entries from the Pull Request list, it does not enable to pull entries from the issues.

So this option does not seem appropriate.

I suggest to manually add a section for open critical and high severity bugs. See example https://github.com/NASA-PDS/registry-api/releases/edit/v1.2.0

**Comment by jordanpadams** [comment]
@tloubrieu-jpl added this to sprint backlog since we said we were going to do it. let me know if we should defer

**Comment by tloubrieu-jpl** [comment]
The proposal is to add the version label to the open bugs at the time of a release (see command created by the PR https://github.com/NASA-PDS/lasso-issues/pull/4).

The command could be called automatically by roundup for stable releases. See ticket https://github.com/NASA-PDS/roundup-action/issues/128

Then the following text (for example) need to be added manually at the end of the release notes: 
**Known Bugs** and possible workarounds:  [v1.3.1 known bugs](https://github.com/NASA-PDS/registry-api/issues?q=is%3Aissue+label%3Av1.3.1)

**Comment by tloubrieu-jpl** [comment]
Re-open because one sub-ticket is not closed.

**Comment by jordanpadams** [comment]
All sub-tasks completed
