### ISSUE TITLE
[ds-view] Add link to DOI page on each landing page JSP

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#5]
**Is your feature request related to a problem? Please describe.**
We need to add a `Data Object Identifier (DOI)` row to each of the landing pages.

Right now, to stage this change, let's just link to this TBD non-existent page: https://pds.nasa.gov/datastandards/citing/doi

The landing pages that need to be updated with new `Data Object Identifier (DOI)` row in the output:

- [x] viewDataset.jsp - Add new row just below `Citation` row
- [x] viewBundle.jsp - Add new row just above `Author List` at top of the `Citation` section
- [x] viewCollection.jsp - Add new row just above `Author List` at top of the `Citation` section 
- [x] viewDocument.jsp - Add new row just above `Author List` at top of the `Citation` section
- [x] all 4 - might as well remove the double menu while you are at it :-)

**Comment by c-suh** [comment]
PR has been opened at https://github.jpl.nasa.gov/PDSEN/pds4-java/pull/133 but am unable to package this into a war. Am getting the following error:

> [ERROR] Failed to execute goal on project ds-view: Could not resolve dependencies for project gov.nasa.pds.2010.portal:ds-view:war:2.13.0: Failed to collect dependencies at gov.nasa.pds.2010.registry:registry-core:jar:1.16.0: Failed to read artifact descriptor for gov.nasa.pds.2010.registry:registry-core:jar:1.16.0: Could not transfer artifact gov.nasa.pds.2010.registry:registry-core:pom:1.16.0 from/to pds-repo (https://pds-cm.jpl.nasa.gov/maven2): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

I've added the root certificate to my JRE truststore but am still encountering this error. Have reached out to @jordanpadams to see if I'm missing anything in my config or anything else.

**Comment by jordanpadams** [comment]
@c-suh per slack:

1. go to `pds4-java/registry-legacy` directory and do a `mvn clean install` - this installs the registry into your local maven repo
2. go to the `portal/ds-view` directory and do a `mvn clean install` or `mvn clean package` - this will build the package and grab your local maven jar

I had to comment out a bunch of parent references that were throwing everything off, but I think we should be good to go.

**Comment by c-suh** [comment]
@jordanpadams thank you; that did the trick. I already had the parent references commented out, but having registry-legacy build the missing jar rather than getting it from pds-repo was what I needed. I'll have this deployed to gamma soon for testing and review.

**Comment by c-suh** [comment]
@tloubrieu-jpl or @jordanpadams I do not have the permissions to move this issue (from this repo) on the board, but this is ready for view.

- https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Aapollo_seismic_event_catalog&version=1.0
- https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewCollection.jsp?identifier=urn%3Anasa%3Apds%3Aa17lsg_raw_arcsav%3Adocument&version=1.0
- https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewDataset.jsp?dsid=ODY-M-THM-5-VISGEO-V1.0

**Comment by jordanpadams** [comment]
@c-suh we will probably need to hold off on deploying this until we actually get this web page working: https://pds.nasa.gov/datastandards/citing/doi .

for https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Aapollo_seismic_event_catalog&version=1.0, how did the DOI actually appear? Is that actually in the search results? that would be awesome if that was true.

for https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewDataset.jsp?dsid=ODY-M-THM-5-VISGEO-V1.0, this looks like something may have gotten screwed up?

btw, you should now have permissions.

**Comment by c-suh** [comment]
@jordanpadams thank you for the permissions!

Yes, a citation DOI key already exists in the schema :] For ones that don't have any value, I inserted the placeholder link. 

Oops, sorry about that. I've moved this back to 'In Progress' and will address this soon.

**Comment by c-suh** [comment]
@jordanpadams sorry for the delay! I pushed a fix and added @tloubrieu-jpl as a reviewer, but let me know if there is anybody else I can add to help this along.

To clarify the above statement: Citation DOI exists in some of the schemas. I'm looking it now and will see if I can provide more details.

**Comment by jordanpadams** [comment]
looks great! let's leave this open as "blocked" until we are able to complete NASA-PDS/pds-doi-ui#25

**Comment by jordanpadams** [comment]
@c-suh if you have time this week, I think I would like to roll out these updates, even if they are not entirely complete

**Comment by jordanpadams** [comment]
here are some final updates we can work on to get this rolled out:
- [ ] update the DOI text to link to the doi.org web page, e.g [10.17189/1520573](https://doi.org/10.17189/1520573)
- [ ] if a DOI cannot be found, let's just put "Unknown. Please contact the [PDS Operator](https://pds.nasa.gov/?feedback=true) for assistance."

for PDS3 data sets, you mentioned that the DOI information does not show up in the registry?

**Comment by c-suh** [comment]
@jordanpadams please verify the changes are good to go operational:
- https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewCollection.jsp?identifier=urn:nasa:pds:apollo_seismic_event_catalog:data
- https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewDataset.jsp?dsid=ODY-M-THM-5-VISGEO-V1.0

**Comment by jordanpadams** [comment]
@c-suh good for merge!

**Comment by c-suh** [comment]
@jordanpadams, I don't have the permissions to merge https://github.jpl.nasa.gov/PDSEN/pds4-java/pull/133 (or https://github.jpl.nasa.gov/PDSEN/pds4-java/pull/134).

**Comment by jordanpadams** [comment]
@c-suh just gave you admin on that repo

**Comment by tloubrieu-jpl** [comment]
Should change "DATA OBJECT IDENTIFIER (DOI)" to digital...

**Comment by c-suh** [comment]
Fixed and deployed!
