### ISSUE TITLE
Upgrade our issue templates to be issue forms

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#56]
## 💡 Description

https://nasa-ammos.github.io/slim/documentation/starter-kits/#github-issues-forms

**Comment by jordanpadams** [comment]
Most have been updated per https://github.com/NASA-PDS/.github/commit/ff7ce6c3a193791832613201eac153be4f5c97c4

**Comment by nutjob4life** [comment]
Thanks for tackling this @jordanpadams. They look great.

**Comment by jordanpadams** [comment]
@nutjob4life I saw them demoed and they looked so fun I had to play around with them 😄
