### ISSUE TITLE
Develop ISA for Data Upload Manager to enable SBN-PSI to deliver data to the cloud

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#79]

**Comment by nutjob4life** [comment]
Underway.

**Comment by jordanpadams** [comment]
Status: Document is ongoing with hopefully deliver to SAs and SBN team by end of week

**Comment by tloubrieu-jpl** [comment]
@jordanpadams is answering the comments.

**Comment by jordanpadams** [comment]
Decided not to pursue a specific ISA for SBN-PSI, and will just create a detailed ISA for all the nodes. https://github.com/NASA-PDS/software-issues-repo/issues/73
