### ISSUE TITLE
Upgrade Legacy Registry Tools and Services to Fix Vulnerability

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#80]
## 💡 Description

Vulnerability identified on operational services. Need to fix and upgrade:

### Services impacted
* Harvest Legacy - https://github.com/NASA-PDS/harvest-legacy
* Registry / Search Service - https://github.com/NASA-PDS/registry-mgr-legacy

## For PDS3 data
* Catalog Tool
  * Storage Service
  * Product Service

Indirectly related downstream:
* Keyword Search
* DS View

## Sub-tasks
- https://github.com/NASA-PDS/registry-legacy-solr/issues/84
- https://github.com/NASA-PDS/harvest-legacy/issues/7
- https://github.com/NASA-PDS/harvest-legacy/issues/6
- https://github.com/NASA-PDS/search-ui-legacy/issues/1
- https://github.com/NASA-PDS/ds-view/issues/3
- https://github.com/NASA-PDS/registry-legacy-solr/issues/95
- https://github.com/NASA-PDS/operations/issues/431
- https://github.com/NASA-PDS/operations/issues/461
- https://github.com/NASA-PDS/search-ui-legacy/issues/5

**Comment by nutjob4life** [comment]
Related: [this pull request](https://github.com/NASA-PDS/registry-pds3-catalog/pull/5)

**Comment by jordanpadams** [comment]
📆 September status: Work is underway with final implementation and testing completing this sprint, and deployment planned for next sprint.

**Comment by nutjob4life** [comment]
Related: [this pull request](https://github.com/NASA-PDS/registry-harvest-service/pull/34)

**Comment by jordanpadams** [comment]
Status: @nutjob4life working on tagging and releasing these with roundup

**Comment by nutjob4life** [comment]
Related: [this pull request](https://github.com/NASA-PDS/registry-mgr-legacy/pull/22) (yes, there are more and more of these!)

**Comment by jordanpadams** [comment]
📆 October status: Implementation completed. Running into bugs testing on staging machines, but still on schedule for production deployment at end of sprint.

**Comment by jordanpadams** [comment]
📆 November status: Deployment delayed 1 sprint due to permissions issues. Expected completion in January. This is an operations task so no impact on overall system delivery.

**Comment by jordanpadams** [comment]
📆 December status: Testing in progress. This is an operations task so no impact on overall system delivery.

**Comment by jordanpadams** [comment]
📆 01/2024 status: delayed due to IT Security concerns needing to be addressed. https://github.com/NASA-PDS/search-ui-legacy/issues/5 is pending. no impact on delivery,

**Comment by tloubrieu-jpl** [comment]
Waiting for response of the SAs (DSIO-4952)

**Comment by jordanpadams** [comment]
Unblocked by SSL issue we were seeing in Tomcat. New DSIO-5364 ticket created to update reverse proxies to connect with UI.

**Comment by nutjob4life** [comment]
Jordan also fixed a quick bug and is working next on getting reverse-proxies set up to test with UI.

**Comment by jordanpadams** [comment]
I think this is actually finally done! only catch is search-ui-legacy release is failing for some reason, but I think that is an issue with GitHub, and I just built and tagged locally for now. https://github.com/NASA-PDS/search-ui-legacy/actions/runs/8013573311

But here is what the keyword search now looks like hooked up to search-ui-legacy:

<img width="937" alt="Screenshot 2024-02-22 at 5 56 03 PM" src="https://github.com/NASA-PDS/software-issues-repo/assets/33492486/49b8d66e-0dde-42ea-871a-900ab25c0cd9">

**Comment by jordanpadams** [comment]
NOTE: Looks like there is no PDS3 data. so we need to reload all of that.
