### ISSUE TITLE
Tag Software for B14.0 I&T Delivery

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/PDS-Software-Issues-Repo#84]
## 💡 Description

Release stable version for PDS EN tools

**roundup releases (github, pypi, maven)**
(first checkbox = released, second checkbox = in the software summary)

:sunny: Done (release, release notes)
⛅ : Release made, release notes not done
:cloud: not started

- ☀️   pds4-information-model 14.3.0
- ☀️  pds4-jparser 2.6.0
- ☀️  validate, 3.3.0
- ☀️   registry-common 1.5.1
- ☀️   harvest (update registry-common dependency) 3.8.1
- ☀️  registry-mgr (update registry-common dependency) 4.6.3
- ☀️  registry-loader (update harvest & registry-mgr dependency) 0.4.1
- ☀️  registry-harvest-service 1.2.1
- ☀️  registry-crawler-service 1.1.0
- ☀️  registry-harvest-cli 1.1.0
- ☀️  registry-sweeper 1.2.0, blocked because dependency need to be on pypi, request made https://github.com/o19s/solr-to-es/issues/23, workaround with temporary package used
- ☀️  registry-api 1.3.1
- ☀️  registry 1.3.1
- ☁️   pds-api, 14.0, documentation to be published
- ☀️  pds-api-client  1.4.0 PR
- ☀️  doi-service 2.4.0
- ☀️  deep-archive 1.1.3 (no updates)
- ☀️  MI-Label 1.4.0
- ☀️   PLAID (no release process)
- ☀️  Transform 1.12.0
- ☀️  Feedback-widget 1.3.0 no update
- ☀️  data-upload-manager 0.3.0
- ☀️   nucleus 0.2.0

Javascript/web releases:

- ☀️    wds-react-legacy 0.3.0
- :sunny:  doi-ui 1.3.0
- ☀️   wds-react, no stable release yet

Docker hub releases

- [x]  registry-loader 
- [x]  registry-harvest-service
- [x]  registry-crawler-service
- [x]  registry-harvest-cli 
- [x] registry-sweepers
- [x]  registry-api 

- [x]  Software release summary

**Comment by jordanpadams** [comment]
@tloubrieu-jpl I saw validate was checked off, but it doesn't look like the tag worked? Also, there is a PR that got mistakenly closed that needs to be merged before we can tag.

**Comment by tloubrieu-jpl** [comment]
Software summary is published on https://nasa-pds.github.io/releases/14.0/index.html
