### ISSUE TITLE
Develop Contingency Plans

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#87]
## 💡 Description

- Production website
- Production registry

**Comment by jordanpadams** [comment]
Draft contingency plan completed. Dependent upon procedures to proceed.

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl @ramesh-maddegoda and @sjoshi-jpl need to contribute by the end of the week.

**Comment by jordanpadams** [comment]
Review complete. Up for signature.

**Comment by jordanpadams** [comment]
Completed, signed, and released. Posted in Alfresco.
